register_screen criada
EmanuelCezardm/SummariesApp pull request #10
Opened 2021-07-24 02:04 UTC by laryssa15s

2021-07-24 15:34 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +import 'package:summaries_app/ui/widgets/app_drawer.dart';
remover importações que não estão sendo utilizadas

2021-07-24 15:40 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +      height: 250,
não usar valores fixos. Crie abaixo da linha 25 "final Size size = MediaQuery.of(context).size;" e utilize o "(size.width ou size.height) * . 'algum numero' , essa variavel size tem as dimensões da tela do celular que abrir o app então utilize ela no lugar dos valores fixos.

2021-07-24 15:40 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +      padding: EdgeInsets.only(top: 100),
diminuir esse padding

2021-07-24 15:43 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +        ],
adicionar "const" antes dos widgets afim de remover os tracejados azuis. Eles não são erros mas deixa-los no código é uma má prática de programação além de poluir muito o código

2021-07-24 15:44 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +          padding: const EdgeInsets.only(left: 5, right: 5, top: 40),
reduzir um pouco o padding top

2021-07-24 15:52 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +        child: Column(
adicionar abaixo da linha 27 "backgroundColor: AppColors.darkBlue," e remover o "color: AppColors.darkBlue," dos Containers.

2021-07-24 15:55 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +      height: 250,
exemplo: height: size.width * .2 vai usar como altura 20% da largura da tela do celular

2021-07-24 15:57 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +          width: double.infinity,
pode remover

2021-07-24 15:58 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +          color: AppColors.darkBlue,
pode remover

2021-07-24 15:58 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +      color: AppColors.darkBlue,
pode remover

2021-07-24 15:59 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                  )),
usar o borderRadius.all no lugar do .only

2021-07-24 16:00 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                    const EdgeInsets.symmetric(vertical: 90, horizontal: 20),
diminuir o EdgeInsets vertical

2021-07-24 16:02 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                      ),
pode remover

2021-07-24 17:47 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +  Widget build(BuildContext context) {
adicionar abaixo "final Size size = MediaQuery.of(context).size;" essa variável size tem as dimensões da tela do celular que abrir o app então utilize ela no lugar dos valores fixos para altura ou largura de widgets grandes.
exemplo: height: size.width * .2 vai usar como altura 20% da largura da tela do celular.
não importa se vc vai usar o .width ou .height nos atributos de altura ou largura pois ambos retornam um double

2021-07-24 17:47 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +    return Scaffold(
adicionar abaixo "backgroundColor: AppColors.darkBlue,".

2021-07-24 17:48 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +          children: [buildTitle(), buildForm()],
adicionar uma virgula após o parênteses de fechamento do buildForm()

2021-07-24 17:51 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +  buildTitle() {
mudar para "_buildTitle(size)

2021-07-24 17:53 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +      height: 250,
substituir os valores fixos pela variavel "size".
exemplo: 
width: size.width,
height: size.height * .3,

2021-07-24 17:56 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +          Text(
adicionar acima do text algo parecido ou como "Container(
            padding: const EdgeInsets.only(left: 15),
            alignment: Alignment.bottomLeft,
            child: GestureDetector(
              onTap: () {
                Navigator.pop(context);
              },
              child: const Icon(
                Icons.arrow_back_ios,
                color: AppColors.offWhite,
                size: 30,
              ),
            ),
          )," 
e adicionar antes do text um "const"

2021-07-24 17:56 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +          SizedBox(
adicionar um "const"

2021-07-24 17:56 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +          Text(
adicionar um "const"

2021-07-24 17:58 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +    return Stack(
substituir o "stack" por um "column" pois não está sendo feita nenhuma sobreposição então o "stack" é meio q inútil aqui

2021-07-24 18:02 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +          color: AppColors.darkBlue,
pode remover os 3

2021-07-24 18:05 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +        Container(
substituir por o "container" por um "padding"

2021-07-24 18:06 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +          padding: const EdgeInsets.only(left: 5, right: 5, top: 40),
substituir por um EdgeInsets. symmetric horizontal entre 20 e 30 vc escolhe

2021-07-24 18:14 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                  )),
substituir por BorderRadius.circular(50),

2021-07-24 18:16 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                    const EdgeInsets.symmetric(vertical: 90, horizontal: 20),
substituir por algo como margin: const EdgeInsets.fromLTRB(20, 25, 20, 40), . os valores vc pode alterar mas não muito longe disso

2021-07-24 18:17 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                        },
criar um método para esse validator

2021-07-24 18:18 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                          prefixIcon: const Icon(
remover o const do icon e colocar no InputDecoration

2021-07-24 18:19 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                      SizedBox(
adicionar const

2021-07-24 18:20 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                        },
criar um método para esse validator

2021-07-24 18:20 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                          prefixIcon: const Icon(
remover o const do icon e colocar no InputDecoration

2021-07-24 18:21 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                      SizedBox(
adicionar const

2021-07-24 18:21 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                        },
criar um método para esse validator

2021-07-24 18:22 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                          },
criar um método para esse validator

2021-07-24 18:23 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                          prefixIcon: const Icon(
remover o const do icon e colocar no InputDecoration

2021-07-24 18:23 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                      SizedBox(
adicionar const

2021-07-24 18:23 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                            prefixIcon: const Icon(
remover o const do icon e colocar no InputDecoration

2021-07-24 18:24 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                      buildButtom(),
pode remover

2021-07-24 18:25 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +              )),
separar com a virgula

2021-07-24 18:27 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +        ),
adicionar abaixo do parênteses do Padding 
const SizedBox(
          height: 40,
        ),
        buildButtom(),
        const SizedBox(
          height: 100,
        ),

2021-07-24 18:29 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +        padding: EdgeInsets.symmetric(vertical: 10, horizontal: 150),
substituir o valor horizontal por algo como 15 ou usar o size para fazer ele quase da largura da tela vc escolhe

2021-07-24 18:30 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +        textStyle: TextStyle(
adicionar const

2021-07-24 18:30 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +          fontSize: 30,
diminuir para 26 ou 24

2021-07-24 18:31 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +      icon: Icon(
adicionar const

2021-07-24 18:31 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +        size: 40,
diminuir para 30 ou 32

2021-07-24 18:31 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +      label: Text('Salvar'),
adicionar const e substituir "salvar" por "cadastrar"

2021-07-24 18:53 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +  final _formKey = GlobalKey<FormState>();
mudar para "final GlobalKey<FormState> _formKey = GlobalKey();"

2021-07-24 18:59 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +      onPressed: () {},
criar um método que retorne a função do onpressed mediante a validação do form algo como:
if (!_formKey.currentState!.validate()) return;

não precisa fazer essa implementação caso ache complicada pq o ideal seria ter a tela de login para isso

2021-07-24 19:02 UTC, EmanuelCezardm requested changes
gostei do código só melhorar alguns detalhes e se atentar a algumas boas práticas de programação, quando mudar o código vai ver que fiz uma pequena mudança no design mas se preferir o seu original pode deixar ele ou se quiser fazer alguma melhoria no meu, sinta-se a vontade

2021-07-24 22:38 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                              Icons.password_sharp,
mudar para "Icons.lock_outline,"

2021-08-01 21:55 UTC, laryssa15s commented on lib/ui/screens/register_screen.dart
> +                  )),
emanu, eu coloquei dessa forma e todas a bordas ficaram arredondadas. Aí usei o "BorderRadius.vertical( top: Radius.circular(50)," para apenas a parte superior ficar

2021-08-02 00:16 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                  )),
esqueci de falar que algumas sugestões de mudança que tinha colocado era pra ver como ficaria se fosse pra ser um quadrado branco com o botão dentro em vez de ser até o fim da tela a parte branca aí tem algumas mudanças que vc pode ignorar

2021-08-02 00:18 UTC, EmanuelCezardm commented on lib/ui/screens/register_screen.dart
> +                  )),
tinha esquecido foi mau

2021-08-02 02:03 UTC, laryssa15s commented on lib/ui/screens/register_screen.dart
> +        Container(
no caso é p substituir o container por um padding?

2021-08-02 02:37 UTC, laryssa15s commented on lib/ui/screens/register_screen.dart
> +                  )),
de boa kkk

2021-08-02 03:11 UTC, laryssa15s commented on lib/ui/screens/register_screen.dart
> +        ),
o botão ficava fora aí fiz de outra forma.

2021-08-04 21:52 UTC, EmanuelCezardm commented
adicionar a opção de visibilidade do campo senha e a autenticação do form no botão de cadastrar

2021-08-14 22:42 UTC, merged